[build]
  base = "flywithashrayaofficialwebpage"
  command = "npm run build"
  publish = ".next"



[context.production.environment]
  NODE_VERSION = "21.5.0"  # Explicitly set Node version

[[plugins]]
  package = "@netlify/plugin-nextjs"

